# Generated by Django 4.2.9 on 2024-04-24 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('truck en route to warehouse', 'truck en route to warehouse'), ('truck waiting for package', 'truck waiting for package'), ('out for delivery', 'out for delivery'), ('delivered', 'delivered')], default='created', max_length=32),
        ),
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('idle', 'idle'), ('traveling', 'traveling'), ('arrive warehouse', 'arrive warehouse'), ('loading', 'loading'), ('delivering', 'delivering')], default='idle', max_length=32),
        ),
    ]
